### ISSUE TITLE
Cannot add a device VIA the GUI

### ISSUE THREAD

**Issue by rickbatton** [cvicente/Netdot#128]
If this is the wrong place to address this my apologies.
I am running Ubuntu Server 14.04
Apache2 version 2.4.7
Netdot 1.0.7
I installed using a number of references:
https://nsrc.org/workshops/2016/rwnog-nmm/netmgmt/en/netdot/exercises-netdot.htm
http://snazone.blogspot.com/2011/07/installing-and-setting-up-netdot-on.html (though not the same version)
I also used the Netdot - Users Manual
I can add devices all day long using the terminal and the updatedevices.pl file HOWEVER
Attempting to add any device from the web GUI presents the error:
Device::_get_snmp_session: Cannot connect to x.x.x.x. Tried communities: public
I can verify that snmp is set up on the device the GUI is attempting to connect to using Paessler SNMP Tester v. 5.2.3
I cannot tell if this is a permissions issue or if the web service is somehow trying to use a different set of MIBs. 
And I am very much a Ubuntu server "noob" so.. I'm struggling. Any help would be much appreciated

**Comment by candlerb** [comment]
* Click "Devices" under "Management"
* Click "[New]" at the right-hand side

You then get two options.

In the left-hand window, you can manually add a device which has SNMP.  You enter the IP address, SNMP version and community.  This does indeed require SNMP to be up and running; the data pulled from SNMP will be used to populate the data.

Alternatively, if the device doesn't talk SNMP, then in the right-hand side you can just add a device manually.  You'll have to populate all the device data by hand.

Now, it seems like you have an SNMP problem between Netdot and your device.  If the remote device doesn't respond, it could be a number of things:

* There is no network path between the Netdot server and the target; or there is a firewall or network filter which is blocking SNMP traffic (UDP 161)
* The community string you are using is wrong, i.e. it's something other than "public"
    * Select "Other" from the community drop-down
    * Enter the correct community string in the text box which appears, replacing the word "Other"
    * Click the left-arrow
* The SNMP version you are using is wrong (Netdot uses v2 by default)
    * Maybe the device is old and only supports v1
    * Maybe the device has been configured only to allow v3
* The device has an ACL which does not permit SNMP from the Netdot server's IP address

I have no idea what "Paessler SNMP Tester" is, but if it's running on a different host that the Netdot server, then it's using a different source IP address, and you may be using a different version of SNMP or community.

ssh into the Netdot server and try testing like this:

```
snmpstatus -v2c -c public x.x.x.x
```

where x.x.x.x is the device.  Do you get a response?  If not, then you need to debug it by trying a different community string and/or different SNMP version and/or different authentication.

If the target device x.x.x.x is a server, then you can run tcpdump (Linux) or wireshark (Windows) on that device to capture the SNMP traffic.  This will confirm whether the messages are getting there, and whether a response is being sent - and may help pin down any network filtering between the Netdot host and this server.

HTH.

**Comment by rickbatton** [comment]
Thank you for your reply. I may not have been overly clear.
I Run the Paessler SNMP Tester on a different machine. But it's only to check to see if snmp is configured and working on another device. (like a switch). 
•Click "Devices" under "Management"
•Click "[New]" at the right-hand side
This is where I get the error.
If I am in the terminal (via ssh or direct via the VM Host) and I run the command: 
updatedevices.pl -B X.X.X.X (X = the device IP address) -I -c PPPPP (P = the community string)
This will work and add (or update) the device.
In this case, it would be the same device that would give an error when attempting to add it in the GUI.
FYI - The IP address is on the same Subnet. 
This is why it's confusing. Same Device that could **not be added** by going to Management -> Devices then clicking NEW **can be added (or updated)** using the updatedevices.pl command via the terminal.
I will try the snmpstatus command as I wasn't aware of that one. Thanks!
Hope this helps explain a bit more..

**Comment by candlerb** [comment]
OK, but the error message says specifically that it's trying the community string "public".  Is PPPPP equal to public?  If not, then maybe you're not correctly selecting the community. Select "Other", replace  the correct community string in the Netbox web interface.

![image](https://user-images.githubusercontent.com/44789/46809259-ffb14a00-cd65-11e8-94b4-646d19fad391.png)

(Actually I was wrong before, *don't* click the `<` button).  If I run tcpdump while doing this, I see the packets being sent out with the correct community:

```
root@netdot:/usr/local/netdot/etc# tcpdump -i eth0 -nn -s0 -v udp port 161 and host 1.1.1.1
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:52:06.159696 IP (tos 0x0, ttl 64, id 24483, offset 0, flags [DF], proto UDP (17), length 73)
    192.168.7.58.41726 > 1.1.1.1.161:  { SNMPv2c C="abcd1234" { GetRequest(28) R=247661557  .1.3.6.1.2.1.1.7.0 } }
14:52:07.160980 IP (tos 0x0, ttl 64, id 24631, offset 0, flags [DF], proto UDP (17), length 73)
    192.168.7.58.41726 > 1.1.1.1.161:  { SNMPv2c C="abcd1234" { GetRequest(28) R=247661557  .1.3.6.1.2.1.1.7.0 } }
14:52:08.162736 IP (tos 0x0, ttl 64, id 24739, offset 0, flags [DF], proto UDP (17), length 73)
    192.168.7.58.41726 > 1.1.1.1.161:  { SNMPv2c C="abcd1234" { GetRequest(28) R=247661558  .1.3.6.1.2.1.1.1.0 } }
```

If you can't get that part to work, you can always edit `/usr/local/netdot/etc/Site.conf` and edit `DEFAULT_SNMPCOMMUNITIES`.  You can list multiple ones like this:

```
DEFAULT_SNMPCOMMUNITIES  =>  ['foofoo','barbar'],
```

(and restart apache). And then I think it will offer them in the web interface to select.

**Comment by rickbatton** [comment]
So the next step in this is I get nothing on my tcpdump
When I attempt to "discover" a device.
![image](https://user-images.githubusercontent.com/44040712/46821215-b94ff100-cd4d-11e8-8fc8-b9610da096ce.png)
![image](https://user-images.githubusercontent.com/44040712/46821247-c1a82c00-cd4d-11e8-9127-68676af2193c.png)
while the command you mentioned is running
![image](https://user-images.githubusercontent.com/44040712/46821169-97566e80-cd4d-11e8-928c-226e4344b15a.png)
You can see nothing shows up. It will sit there until I kill the task.
And to further confirm. I run the script and it works fine.
![image](https://user-images.githubusercontent.com/44040712/46821647-e4871000-cd4e-11e8-94da-8e65051f6441.png)

**Comment by rickbatton** [comment]
Just saw your previous message.. Will try that

**Comment by rickbatton** [comment]
You are now on to something.. I am getting a ton of errors now.. Let me see if I can capture this somehow

**Comment by rickbatton** [comment]
So..... I attempted to send the output to a txt file. Though I get a very long list of messages on the screen (terminal window) the txt file only contains this...
![image](https://user-images.githubusercontent.com/44040712/46822917-66c50380-cd52-11e8-9aea-62c4389a2dd5.png)
I noticed something in the apache error log that looks similar to the output above this.. 
Seeing the "Permission denied" error is the only thing that seems to have some sort of meaning (to me anyway).
Looking at the permissions of the netdot subfolders I have this:
![image](https://user-images.githubusercontent.com/44040712/46823518-0636c600-cd54-11e8-9866-dc79cb1f6a8d.png)


I attached what I believe relevant from the apache logs from when I was working on this last evening. 
[new 1.txt](https://github.com/cvicente/Netdot/files/2470029/new.1.txt)

It is almost like there are some modules missing from something?
Note a number of "Cannot find module BLAH.."
This is where I couldn't figure out if this was a configuration or a permissions thing.

And seriously!! I truly appreciate your help here!!

**Comment by candlerb** [comment]
I think the real error could be earlier than your screenshot shows, since it already has "Failed connection attempts: 5".  Try this:

```
$ script log.txt
$ sudo... (as before)
$ ./updatedevices... (as before)
$ exit
$ exit
```

At this point you'll have a file called log.txt that you can transfer back to your PC using sftp or scp or however you normally do this.  Or at worst, stick it under /var/www/ or /var/www/html/ (can't remember which one Ubuntu 14.04 used) and download it from http://x.x.x.x/log.txt

But if the only errors you see are to do with mibs, and you don't get these when running as root, then maybe it's just permissions on one of the MIB directories; it might be silently failing to open them.  In which case you might get clues from the following:

```
$ strace -f ./updatedevices... 2>strace.out
$ grep "= -1" strace.out
$ egrep "EPERM|EACCES" strace.out
```

You can recursively fix a tree to make all files and directories readable - the following example is for `/usr/share/snmp/mibs` but there will be others in the MIB search path.

```
find /usr/share/snmp/mibs -type d -exec chmod 755 '{}' ';'
find /usr/share/snmp/mibs -type f -exec chmod 644 '{}' ';'
```

**Comment by rickbatton** [comment]
Attached this log from first steps.

[log.txt](https://github.com/cvicente/Netdot/files/2470282/log.txt)

Do these look like just mib errors to you? 

I will work on the second part of your last reply

**Comment by rickbatton** [comment]
Apologies... On running this command:
$ strace -f ./updatedevices... 2>strace.out
$ grep "= -1" strace.out
$ egrep "EPERM|EACCES" strace.out

Should this be run as www-data or as myself/root?

**Comment by candlerb** [comment]
Run as www-data; you're trying to catch any errors on opening files or directories

**Comment by candlerb** [comment]
I don't see anything other than MIB errors in log.txt, so if updatedevices.pl doesn't show those, it could well be a perms issue.

**Comment by rickbatton** [comment]
Permission denied
![image](https://user-images.githubusercontent.com/44040712/46831012-ced21480-cd67-11e8-8bac-f0251f715abe.png)

**Comment by mzagrabe** [comment]
Rick and others,

While we don't use SNMP with Netdot (yet), I did do some digging for our
instance and stumbled across a Debian bug report. It might be relevant:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=602271#20

    """
    Copy the /usr/share/doc/netdisco-mibs-installer/contrib/snmp.conf to
    /etc/snmp/snmp.conf and follow the hints inside the snmp.conf example
    file:

    "Change /usr/local/netdisco to the directory you installed netdisco-mibs
    into..."
    """

Enjoy,

-m

**Comment by rickbatton** [comment]
It was permissions on the netdisco folder I created for the mibs I extracted
I ran the commands requested above:
find /usr/share/snmp/mibs -type d -exec chmod 755 '{}' ';'
find /usr/share/snmp/mibs -type f -exec chmod 644 '{}' ';'

With the addition of:
find /usr/local/netdisco/mibs -type d -exec chmod 755 '{}' ';'
find /usr/local/netdisco/mibs -type f -exec chmod 644 '{}' ';'

And now it seems to work as advertised!! 
I appreciate everyone's help on this and sorry I am so much a noob this may have been easy for those that have worked basic *nix for awhile

**Comment by candlerb** [comment]
Excellent, glad it is working.

For reference: the problem with the `strace` command was where the output was being redirected.  You could have changed it to:

```
$ strace -f ./updatedevices.pl .... 2>/tmp/strace.out
```
