### ISSUE TITLE
deleting MX record also deletes indirect A, AAAA, and PTR records

### ISSUE THREAD

**Issue by mzagrabe** [cvicente/Netdot#130]
Deleting a DNS record that is the target for MX records also deletes the A, AAAA, and PTR records for those systems that have the MX record.

For instance:

foo IN A 10.0.0.1
foo IN MX 10 mail.example.com

Deleting the DNS record mail.example.com also deletes the A record for foo.

**Comment by cvicente** [comment]
Matt, thanks for reporting this. Please review the PR:
https://github.com/cvicente/Netdot/pull/131

**Comment by cvicente** [comment]
Thanks. PR merged.
