### ISSUE TITLE
Ubuntu 18.04.2 install succesful but Error while inserting Ipblock: Can't insert new Ipblock

### ISSUE THREAD

**Issue by jaimerletona** [cvicente/Netdot#143]
When I try to add IP block, obtain this error :

Error while inserting Ipblock: Can't insert new Ipblock: Can't get last insert id at /usr/local/netdot/htdocs/management/ip.html line 330.

If I try to add a Contact, obtain this error:

people.html produced the following error:

Error while inserting Person: Can't insert new Person: Can't get last insert id at /usr/local/netdot/lib/Netdot/UI.pm line 243.
However, the contact appear in the list.

Also, netdot delete or update fine an IPBLOCK or password.
I appreciate any orientation about that

**Comment by candlerb** [comment]
You need to apply a patch to `/usr/share/perl5/Class/DBI.pm` that you can find [here](https://github.com/cvicente/Netdot/issues/48#issuecomment-297634200) from #48

It seems that `Class::DBI` is abandonware, and there's nothing Netdot can do about this short of a major rewrite to use a different library :-(

**Comment by jaimerletona** [comment]
Thanks a lot. It works perfectly fine.
It means that the manual http://htmlpreview.github.io/?https://github.com/cvicente/Netdot/blob/master/doc/manual/netdot-manual.html must to say **3.5 Ubuntu 16.04 and Ubuntu 18.04.2**.
Again, thanks.

**Comment by candlerb** [comment]
It does say "Starting with Ubuntu 16.04", but maybe the heading should be "Ubuntu 16.04 and later"

**Comment by jaimerletona** [comment]
Thanks for the tip. Everything works fine.
