### ISSUE TITLE
Can't insert new DataCache: DBD::mysql::st execute failed 

### ISSUE THREAD

**Issue by jaimerletona** [cvicente/Netdot#145]
Hello everyone. Sorry for my english.
I have two virtual machines, first with ubuntu 10.04 Netdot 0.9.10 with all my data. Second with fresh installation of utunbu 18.04.2 Netdot 1.0.7. 
I did a migration database of 0.9.10 version to 1.0.7. The idea was only migrate data, then, the procedure works almost fine.  I drop the whole tables in the new version in ubuntu 18.04.2 and replace with mysqldump insert the data migrated.

Everything works with netdot, except insert new data. When I try to add new registry or delete an IP address, Netdot says:

Error while inserting DataCache: Can't insert new DataCache: DBD::mysql::st execute failed: Field 'data' doesn't have a default value [for Statement "INSERT INTO datacache (tstamp, name)
VALUES (?, ?)
" with ParamValues: 0=0, 1='iptree4'] at /usr/share/perl5/DBIx/ContextualFetch.pm line 52.

For any advice or orientation, very thankful.

**Comment by cvicente** [comment]
Hola Jaime,

Veo que el proceso de upgrade empieza con la versión 1.0.1. Ni siquiera me acuerdo cuál era el proceso anterior a ese. ;-)

Es muy probable que la tabla `datacache` se haya creado sin valores por defecto. En la DB actual, la definición de la tabla es:

```
mysql -u root -p netdot
...
mysql> describe datacache;
+--------+--------------+------+-----+---------+----------------+
| Field  | Type         | Null | Key | Default | Extra          |
+--------+--------------+------+-----+---------+----------------+
| data   | longblob     | NO   |     | NULL    |                |
| id     | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name   | varchar(255) | NO   | UNI | NULL    |                |
| tstamp | bigint(20)   | NO   |     | NULL    |                |
+--------+--------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

Verifica en tu DB, y si no es igual, puedes hacer lo siguiente desde una sesión de cliente de mysql:

```
mysql> ALTER TABLE datacache MODIFY COLUMN data longblob DEFAULT NULL;
```

**Comment by jaimerletona** [comment]
Gracias Carlos.
En efecto mi data mysql es identico al menos en esa parte:
mysql> use netdot;
Database changed

```
mysql> describe datacache;
+--------+--------------+------+-----+---------+----------------+
| Field  | Type         | Null | Key | Default | Extra          |
+--------+--------------+------+-----+---------+----------------+
| data   | longblob     | NO   |     | NULL    |                |
| id     | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name   | varchar(255) | NO   | UNI | NULL    |                |
| tstamp | bigint(20)   | NO   |     | NULL    |                |
+--------+--------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)

```
De igual forma corrí la modificación:

```
mysql> ALTER TABLE datacache MODIFY COLUMN data longblob DEFAULT NULL;
Query OK, 0 rows affected (0.16 sec)
Records: 0  Duplicates: 0  Warnings: 0

```
El proceso de convertir mi DB a la última versión me interesa, sobre todo por la versión tan viejita que tengo del sistema operativo, además de las prestaciones de netdot nuevas. Yo puedo repetir el proceso, quizá hay una ruta de migración que deba respetar. Atento a sugerencias y recomendaciones.

**Comment by jaimerletona** [comment]
Un momento, a pesar de ello, ahora sí que puedo grabar información. Creo que sí funcionó después de todo. Muy agradecido con vos Carlos.
