### ISSUE TITLE
Delete device error

### ISSUE THREAD

**Issue by Sivolen** [cvicente/Netdot#179]
Hi!
I have a problem when I remove the device
```

 delete.html produced the following error:


Transaction aborted: Can't delete 11691237: DBD::mysql::st execute failed: Writing one row to the row-based binary log failed [for Statement "DELETE
FROM   fwtableentry
WHERE  id=?
" with ParamValues: 0=11691237] at /usr/share/perl5/DBIx/ContextualFetch.pm line 52,  line 4.
```

how can it be solved?

**Comment by cvicente** [comment]
I'm not familiar with that error, but it appears to be an issue with your MySQL setup. Perhaps try increasing the size of max_binlog_cache_size in your MySQL config.

**Comment by Sivolen** [comment]
Hello, I disabled the binlog operation in the settings and the problem is gone
