### ISSUE TITLE
NetdotLDAPServer2 is ignored

### ISSUE THREAD

**Issue by ksyz** [cvicente/Netdot#54]
Option `NetdotLDAPServer2` is ignored, as there is a typo in configuration handler. It just gets overridden by primary server value: f16506611f717edc36e877f75bcd0257f61393d8

**Comment by cvicente** [comment]
Fixed in https://github.com/cvicente/Netdot/commit/91d3891e669e5b2464d22d89e3bb796ed09e95f0
