### ISSUE TITLE
PhysAddr->format_address_db undefined

### ISSUE THREAD

**Issue by vink78** [cvicente/Netdot#76]
It seems this function does not exist.

It seems to be possible to call PhysAddr->_format_address_db instead?

Regards,

Vincent

**Comment by cvicente** [comment]
It looks like this method was named thinking that it would be internal to the class, but since it is called from other places, I believe the best option is to rename it. 

PR on its way

**Comment by cvicente** [comment]
@vink78 Please review if you have a chance:

https://github.com/cvicente/Netdot/pull/77

**Comment by vink78** [comment]
Hi Carlos, tested it, and, it fixes my issue ;)
Thank you
